feat : NG_BACK_END-166
nrhirano/docker-compose-practice pull request #1
Opened 2022-01-24 06:32 UTC by nrhirano

#### 関連タスク
- [NG_BACK_END-166 【第2回スクール docker-compose.ymlを作成する(実践編) 】 (平野様)](https://nishio-pj.backlog.com/view/NG_BACK_END-166)

#### PR 概要
- Q2スクール docker-compose.ymlを作成する(実践編)です。

#### 相談したい項目・保留した項目
- なし

#### 参考資料
- なし

2022-01-24 07:53 UTC, EikoNakashima requested changes

2022-01-24 07:53 UTC, EikoNakashima commented on docker-compose.yml
> +      - DATABASE_PASSWORD=password
```suggestion
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=password
```

このように書く事が一般的です。
元々の記載でも動きましたでしょうか？

2022-01-24 23:58 UTC, nrhirano commented on docker-compose.yml
> +      - DATABASE_PASSWORD=password
ご指摘ありがとうございます。
確認したところ正常に動作していなかったため、
記載頂いた内容で修正するように致します。

2022-01-25 01:23 UTC, GenkiHirano approved these changes
LGTM 🐱

2022-01-26 01:31 UTC, EikoNakashima approved these changes
LGTM❄️

2022-01-26 05:47 UTC, merged